[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# foundry.toml

[profile.remappings]
'openzeppelin-contracts/' = 'lib/openzeppelin-contracts/'
'@chainlink/contracts/' = 'lib/chainlink/contracts'
'aave-v3-core/' = 'lib/aave-v3-core/'


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
